---
abstract: 'Extract meta information from image files'
author:
  - 'Slaven Rezic'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Image::Info
name: Image-Info
no_index:
  directory:
    - dev
    - img
    - inc
    - t
recommends:
  Image::Xbm: 1
  Image::Xpm: 1
  XML::LibXML::Reader: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git@github.com:eserte/image-info.git
version: 1.28_50
